<?php

/**
 * Created by PhpStorm.
 * User: wilton
 * Date: 12/19/2016
 * Time: 2:44 PM
 */
class A
{
    static $a = 1;

    static function modified_a()
    {
        return self::$a + 10;
    }

    public  function hello(){
        echo "hello <br/>";
    }
}

class B extends A
{
    static function attr_test(){
        echo parent::$a;
    }

    static function method_test(){
        echo parent::modified_a();
    }

    public function hello()
    {
        echo "************<br/>";
        parent::hello(); // TODO: Change the autogenerated stub
        echo "************";
    }

}


echo B::$a ."<br/>";
echo B::modified_a() ."<br/>";

$object = new B();
$object->hello();
